- hosts: mc_server
  roles:
    - role: geerlingguy.java
      become: yes
      java_packages:
        - java-1.8.0-openjdk
  tasks:
    - name: Ensure minecraft directory
      become: yes
      file:
        path: /var/lib/minecraft/
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0775'
    - name: Download server.jar
      get_url:
        url: https://launcher.mojang.com/v1/objects/a412fd69db1f81db3f511c1463fd304675244077/server.jar
        dest: /var/lib/minecraft/server.jar
        mode: '0775'
    - name: Copy start.sh with owner and permissions
      copy:
        src: src/start.sh
        dest: /var/lib/minecraft/start.sh
        owner: ec2-user
        group: ec2-user
        mode: '0755'